server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:server.p12
    key-store-password: 123456
    key-alias: ehrcloud
    key-store-type: PKCS12
    trust-store: classpath:truststore.p12
    trust-store-password: 123456
    trust-store-type: PKCS12
    client-auth: need

spring:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/my_database?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
      username: root
      password: zym07966324345
      driver-class-name: com.mysql.cj.jdbc.Driver
    oracle:
      url: jdbc:oracle:thin:@localhost:1521:ORCL
      username: your_oracle_username
      password: your_oracle_password
      driver-class-name: oracle.jdbc.OracleDriver