#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:server.keystore  # 你的服务端私钥
#    key-store-password: yourpassword
#    key-password: yourpassword
#    trust-store: classpath:truststore.jks # CA证书
#    trust-store-password: yourpassword
#    client-auth: need

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: zym07966324345
    driver-class-name: com.mysql.cj.jdbc.Driver